[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fastzip"
version = "1.0.0"
description = "Fast zipping tool"
authors = [
    {name = "Lonefrogg"}
]


dependencies = [
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib"
]

[project.scripts]
fastzip = "fastzip.cli:main"